#!/bin/sh

set -e

export NVM_DIR=/usr/local/nvm

# Include nvm
. "/usr/local/nvm/nvm.sh"

# Read env file
export $(grep -v '^#' "/etc/transai/connector-orchestrator.conf" | xargs -d '\n')

# Start the Node.js application
bash -c 'npx node "/usr/local/share/transai/connector-orchestrator/main.js" \
    > >(tee -a /var/log/transai/connector-orchestrator.log) \
    2> >(tee -a /var/log/transai/connector-orchestrator.error.log >&2)'
