#!/bin/sh

set -e

export NVM_DIR=/usr/local/nvm

# Make transai user owner of the files
chown -R transai:transai /usr/local/share/transai

. /usr/share/debconf/confmodule

case "$1" in
    configure)
        # Fetch values from debconf
        db_get transai-connector-orchestrator/management-api-client-id
        MANAGEMENT_API_CLIENT_ID="$RET"

        db_get transai-connector-orchestrator/management-api-client-secret
        MANAGEMENT_API_CLIENT_SECRET="$RET"

        db_get transai-connector-orchestrator/management-api-url
        MANAGEMENT_API_URL="$RET"

        db_get transai-connector-orchestrator/authentication-audience
        AUDIENCE="$RET"

        db_get transai-connector-orchestrator/authentication-domain
        IDENTITY_PROVIDER_URL="$RET"

        db_get transai-connector-orchestrator/authentication-org-id
        AUTH0_ORG_IDENTIFIER="$RET"

        db_get transai-connector-orchestrator/tenant-id
        TENANT_IDENTIFIER="$RET"

        # Create config directory if needed
        CONFIG_DIR="/etc/transai"
        CONFIG_FILE="$CONFIG_DIR/connector-orchestrator.conf"
        mkdir -p "$CONFIG_DIR"

        cat > "$CONFIG_FILE" <<EOF
MANAGEMENT_API_CLIENT_ID="$MANAGEMENT_API_CLIENT_ID"
MANAGEMENT_API_CLIENT_SECRET="$MANAGEMENT_API_CLIENT_SECRET"
MANAGEMENT_API_URL="$MANAGEMENT_API_URL"
IDENTITY_PROVIDER_URL="$IDENTITY_PROVIDER_URL"
AUTH0_ORG_IDENTIFIER="$AUTH0_ORG_IDENTIFIER"
AUDIENCE="$AUDIENCE"
TENANT_IDENTIFIER="$TENANT_IDENTIFIER"
EOF

        chown transai:transai "$CONFIG_FILE"
        ;;
esac
db_stop

# Install NVM (Node Version Manager)
mkdir /usr/local/nvm
curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh" | bash
. "$NVM_DIR/nvm.sh"

# Install Node.js using NVM
nvm install "24.11"

# Re-install node modules
su transai -c 'cd $HOME/connector-orchestrator; npm install --no-save'

# Reload the systemd manager configuration, enable and start service
if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload
  systemctl enable transai.service
  systemctl start transai.service
fi
