#!/bin/sh

# Stop systemctl
if command -v systemctl >/dev/null 2>&1; then
  systemctl stop transai.service
  systemctl disable transai.service
fi

# Remove symlink
rm /usr/local/bin/transai-connector-orchestrator
rm -rf /usr/local/share/transai/connector-orchestrator

# Remove user if it exists
if id "transai" >/dev/null 2>&1; then
    if command -v deluser >/dev/null 2>&1; then
        deluser "transai"
    elif command -v userdel >/dev/null 2>&1; then
        userdel "transai"
    else
        echo "Neither deluser nor userdel found. Cannot delete user." >&2
        exit 1
    fi
fi
