#!/bin/sh

set -e

NVM_DIR=/usr/local/nvm
. "$NVM_DIR/nvm.sh"

# Read env file
source "/etc/transai/connector-orchestrator.conf"

# Start the Node.js application
node "/usr/local/share/transai/connector-orchestrator/main.js"
