#!/bin/sh

set -e

# Load debconf library
. /usr/share/debconf/confmodule

# Ask questions. Priority can be: low, medium, high, critical.
db_input high transai-connector-orchestrator/management-api-client-id || true
db_input high transai-connector-orchestrator/management-api-client-secret || true
db_input medium transai-connector-orchestrator/management-api-url || true
db_input medium transai-connector-orchestrator/authentication-domain || true
db_input medium transai-connector-orchestrator/authentication-audience || true
db_input high transai-connector-orchestrator/tenant-id || true

db_go || true

exit 0
