#!/bin/sh

set -e

# Create the needed user, if it doesn't already exist
if ! id "transai" >/dev/null 2>&1; then
    if command -v adduser >/dev/null 2>&1; then
        adduser --system --home-dir /usr/local/share/transai --user-group "transai"
    elif command -v useradd >/dev/null 2>&1; then
        useradd --system --home-dir /usr/local/share/transai --base-dir /usr/local/share/transai --user-group --shell /usr/bin/sh "transai"
    else
        echo "Neither adduser nor useradd found. Cannot create user." >&2
        exit 1
    fi
fi
